services:
  knep:
    image: kong/kong-native-event-proxy-dev@sha256:11b35b6c40ab093dd13196e408b8fdf10b595df2924f8fe39a232955e8ae25b9
    container_name: knep
    ports:
      - "8080:8080"
      - "8443:8443"
      - "19092-19095:19092-19095"
    env_file: "knep.env"
    environment:
      KNEP__RUNTIME__DRAIN_DURATION: 1s # makes shutdown quicker, not recommended to be set like this in production 
      KNEP__OBSERVABILITY__LOG_FLAGS: "info,knep=debug" # Uncomment for debug logging
    healthcheck:
      test: curl -f http://localhost:8080/health/probes/liveness
      interval: 10s
      timeout: 5s
      retries: 5